[package]
name = "jpci"
description = "Interpreter with REPL interface"
version = "0.0.1"
authors = ["squeakbug <squeakbug73@outlook.com>"]
edition = "2021"

[dependencies]
core = { workspace = true }
rpds = { workspace = true }
thiserror = { workspace = true }
