[package]
name = "jpc"
description = "Pascal compiler"
version = "0.0.1"
authors = ["squeakbug <squeakbug73@outlook.com>"]
edition = "2021"

[dependencies]
core = { workspace = true }
clap = { workspace = true }
