[package]
name = "core"
version = "0.0.1"
authors = ["squeakbug <squeakbug73@outlook.com>"]
edition = "2021"

[dependencies]
thiserror = { workspace = true }
lazy_static = { workspace = true }
termcolor = { workspace = true }
codespan-reporting = { workspace = true }
camino = { workspace = true }
